; Part of my extensions.conf for Asterisk PBX
; describing use of tools for messaging written by me
; (called SMS Suite).
;
; In my configuration, I use "9000" number as a SMS Centre.
; Please change it to meet Your needs.
;
; I've created "scripts" folder in my "/etc/asterisk"
; path for all the software written by me for use with dialplan.
; If You wish to have them in other place - simply change
; globals a bit :)
;
; Please do not repost this sample configuration anywhere
; without information about its original author (lines below).
; Thank You :)
;
; This sample configuration part was created
; by Bartłomiej "Magnetic-Fox" Węgrzyn, 2023-2026

[globals]

; Main settings

CENTRE_CALLERID="YourPBX" <sip:your_number>

; Scripts

SMSPROCESS=/etc/asterisk/scripts/smsProcess.py
AGIGETCHANINFO=/etc/asterisk/scripts/agiGetChanInfo.py
AGIPOSTSMS=/etc/asterisk/scripts/agiPostSMS.py

; String table

MESSAGEERR_1=Message delivery to
MESSAGEERR_2=failed.

MSGERRCAUSE1=User is not logged in.
MSGERRCAUSE2=There is no such number.
MSGERRCAUSE3=User has disabled messaging system.



; SMS Centre
[sms-centre]
exten = 9000,1,Answer()
same = n,SMS(${CALLERID(num)},sa)
same = n,System(${SMSPROCESS})
same = n,Hangup()



; SIP IM context
[messages]
exten => _X.,1,AGI(${AGIGETCHANINFO})

same => n,Set(MSGFROMPART=${CUT(MESSAGE_DATA(from),:,2)})
same => n,Set(MESSAGE_FROM=${CUT(MSGFROMPART,@,1)})

same => n,GotoIf($["${MSG_CHAN_OPT}" == "T"]?sipmsgsend)
same => n,GotoIf($["${MSG_CHAN_OPT}" == "U"]?sipmsgfail2)
same => n,GotoIf($["${MSG_CHAN_OPT}" == "N"]?sipmsgfail3)
same => n,GotoIf($["${MSG_CHAN_OPT}" == "S"]?sipmsgsms)
same => n,GotoIf($["${MSG_CHAN_OPT}" == "F"]?sipmsgsms)
same => n,GotoIf($["${MSG_CHAN_OPT}" == "V"]?sipmsgsms)
same => n,GotoIf($["${MSG_CHAN_OPT}" == "C"]?sipmsgsms)
same => n(sipmsgfinish),Hangup()

; Send SIP message
same => n(sipmsgsend),Set(WHOLE_DOMAIN=${CUT(MSGFROMPART,@,2)})
same => n,Set(MY_DOMAIN=${CUT(WHOLE_DOMAIN,>,1)})
same => n,Set(CLEAR_TO=pjsip:${EXTEN})
same => n,Set(CLEAR_FROM=sip:${MESSAGE_FROM}@${MY_DOMAIN})
same => n,Set(MESSAGE(from)=${CLEAR_FROM})
same => n,Set(MESSAGE(to)=sip:${EXTEN}@${MY_DOMAIN})
same => n,MessageSend(${CLEAR_TO}, ${CLEAR_FROM})
same => n,GotoIf($["${MESSAGE_SEND_STATUS}" != "SUCCESS"]?sipmsgfail)
same => n,Hangup()

; Post as an SMS and process
same => n(sipmsgsms),Set(MSG_B64=${BASE64_ENCODE(${MESSAGE(body)})})
same => n,AGI(${AGIPOSTSMS})
same => n,System(${SMSPROCESS})
same => n,Hangup()

; Fail conditions
same => n(sipmsgfail),Set(MESSAGE(body)=${MESSAGEERR_1} ${EXTEN} ${MESSAGEERR_2} ${MSGERRCAUSE1})
same => n,Goto(sipmsgproc)

same => n(sipmsgfail2),Set(MESSAGE(body)=${MESSAGEERR_1} ${EXTEN} ${MESSAGEERR_2} ${MSGERRCAUSE2})
same => n,Goto(sipmsgproc)

same => n(sipmsgfail3),Set(MESSAGE(body)=${MESSAGEERR_1} ${EXTEN} ${MESSAGEERR_2} ${MSGERRCAUSE3})
same => n,Goto(sipmsgproc)

; Error send procedure
same => n(sipmsgproc),AGI(${AGIGETCHANINFO})
same => n,GotoIf($["${MSG_CHAN_OPT}" == "T"]?sipmsgerrorsend:sipmsgerrorfinish)
same => n(sipmsgerrorsend),Set(MESSAGE(from)=${CENTRE_CALLERID})
same => n,MessageSend(pjsip:${MESSAGE_FROM})
same => n(sipmsgerrorfinish),Hangup()
